---
title: "Finding IPCC Ensemble"
author: "Joe Brown"
date: "2025-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal

## Loading data

```{r}

# load result 
model_result <- readRDS("output/model_results/initial_result5k.RDS")

```

source helper functions:
```{r}
# source utils
source("set-up/utils.R")
source("set-up/libraries.R")
```

Subset data to include `global_tas` and normalize data to AR6 reference period:
```{r}
## subset to only include global_tas
gsat_data <- lapply(names(model_result), function(scenario_name) {
  
  # copy data
  df <- model_result[[scenario_name]]
  
  # Count NAs before removal
  na_count <- sum(is.na(df))
  print(paste("Number of NAs in", scenario_name, "data:", na_count))
  
  # subset data to include only global temperature
  subset_data = subset(na.omit(df), variable == "global_tas")
  
  subset_data$scenario <- scenario_name
  
  return(subset_data)
})

## copy list element names
names(gsat_data) <- names(model_result)

## normalize gsat data
gsat_data_normalized <- lapply(gsat_data, function(df) {
  
  normalize_to_reference(df, reference_start = 1995, reference_end = 2014)
  
}) 

```
Visulize full ensemble of gsat data:
```{r}
gsat_data_normalized_df <- do.call(rbind, gsat_data_normalized)

full_ensemble_plot <- ggplot() +
  geom_line(data = subset(gsat_data_normalized_df, year > 1994 & year <2101), 
            aes(x = year, y = value, group = run_number), 
            linewidth = 0.5, color = "lightblue") +
  facet_wrap(~scenario)

full_ensemble_plot
```

